ln -s ~/dotfiles/vim ~/.vim 
ln -s ~/dotfiles/vim/vimrc ~/.vimrc 
ln -s ~/dotfiles/vim/gvimrc ~/.gvimrc 
ln -s ~/dotfiles/bashrc ~/.bashrc 
ln -s ~/dotfiles/zshrc ~/.zshrc 
ln -s ~/dotfiles/Xmodmap ~/.Xmodmap
ln -s ~/dotfiles/ackrc ~/.ackrc 
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf 
ln -s ~/dotfiles/xmonad ~/.xmonad
